### ISSUE TITLE
Have you called init_node()?

### ISSUE THREAD

**Issue by git-chenjiqing** [stoddabr/ros_flask#1]
Are you sure this is feasible

**Comment by stoddabr** [comment]
`init_node()` is run in a secondary thread which is part of the magic that makes this work. It's nested in a lambda function so it's not obvious https://github.com/stoddabr/ros_flask/blob/3a7d1481464a97ff5a5819932121eec16092c72a/src/main.py#L18

If there's an issue with an implementation I'd be happy to work on a fix, but otherwise I'm going to close this issue.
